### ISSUE TITLE
Error Mflow

### ISSUE THREAD

**Issue by Mlondo** [ekholabs/ai-engineering#1]
Good day,

Please help with the following error, can't get it right.
Starting ekholabs-minio      ... done
Starting ekholabs-sftp       ... done
Starting ekholabs-jupyterlab ... done
Starting ekholabs-mlflow     ... done
Attaching to ekholabs-sftp, ekholabs-minio, ekholabs-jupyterlab, ekholabs-mlflow
ekholabs-jupyterlab    | Executing the command: jupyter notebook
ekholabs-sftp          | [/entrypoint] Executing sshd
ekholabs-sftp          | Server listening on 0.0.0.0 port 22.
ekholabs-sftp          | Server listening on :: port 22.
ekholabs-jupyterlab    | [I 10:14:46.087 NotebookApp] JupyterLab extension loaded from /opt/conda/lib/python3.7/site-packages/jupyterlab
ekholabs-jupyterlab    | [I 10:14:46.087 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
ekholabs-jupyterlab    | [I 10:14:46.090 NotebookApp] Serving notebooks from local directory: /ekholabs-notebooks
ekholabs-jupyterlab    | [I 10:14:46.090 NotebookApp] The Jupyter Notebook is running at:
ekholabs-jupyterlab    | [I 10:14:46.090 NotebookApp] http://079c072d56a3:8888/?token=b24d270524dda797584e4635ab82722417ef6c30ccdf16e9
ekholabs-jupyterlab    | [I 10:14:46.090 NotebookApp]  or http://127.0.0.1:8888/?token=b24d270524dda797584e4635ab82722417ef6c30ccdf16e9
ekholabs-jupyterlab    | [I 10:14:46.090 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
ekholabs-jupyterlab    | [C 10:14:46.095 NotebookApp] 
ekholabs-jupyterlab    |     
ekholabs-jupyterlab    |     To access the notebook, open this file in a browser:
ekholabs-jupyterlab    |         file:///home/jovyan/.local/share/jupyter/runtime/nbserver-6-open.html
ekholabs-jupyterlab    |     Or copy and paste one of these URLs:
ekholabs-jupyterlab    |         http://079c072d56a3:8888/?token=b24d270524dda797584e4635ab82722417ef6c30ccdf16e9
ekholabs-jupyterlab    |      or http://127.0.0.1:8888/?token=b24d270524dda797584e4635ab82722417ef6c30ccdf16e9
ekholabs-mlflow        | # ekholabs-sftp:22 SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u4
ekholabs-sftp          | Connection closed by 172.22.0.5 port 56140 [preauth]
ekholabs-mlflow        | # ekholabs-sftp:22 SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u4
ekholabs-mlflow        | # ekholabs-sftp:22 SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u4
ekholabs-sftp          | Unable to negotiate with 172.22.0.5 port 56142: no matching host key type found. Their offer: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521 [preauth]
ekholabs-sftp          | Connection closed by 172.22.0.5 port 56144 [preauth]
ekholabs-minio         | Endpoint:  http://172.22.0.2:9000  http://127.0.0.1:9000
ekholabs-minio         | 
ekholabs-minio         | Browser Access:
ekholabs-minio         |    http://172.22.0.2:9000  http://127.0.0.1:9000
ekholabs-minio         | 
ekholabs-minio         | Object API (Amazon S3 compatible):
ekholabs-minio         |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
ekholabs-minio         |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
ekholabs-minio         |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
ekholabs-minio         |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
ekholabs-minio         |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
ekholabs-mlflow        | /usr/local/lib/python3.7/site-packages/jinja2/utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
ekholabs-mlflow        |   from collections import MutableMapping
ekholabs-mlflow        | /usr/local/lib/python3.7/site-packages/jinja2/runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
ekholabs-mlflow        |   from collections import Mapping
ekholabs-mlflow        | Usage: mlflow server [OPTIONS]
ekholabs-mlflow        | Try "mlflow server --help" for help.
ekholabs-mlflow        | 
ekholabs-mlflow        | Error: no such option: --file-store
ekholabs-mlflow exited with code 2

**Comment by saeed349** [comment]
the latest version of mlflow doesnt have --file-store, instead use --backend-store-uri
or use an older version of mlflow (0.7.0 or below).

**Comment by Mlondo** [comment]
Thanks, I’ll try it out.

**Comment by Mlondo** [comment]
It worked thanks, however I'm unable to accesss my jupyterlab, it says it needs a token but when I paste it, no access still, see my token below:
http://127.0.0.1:8888/login?next=%2Ftree%3Ftoken%3Dd319142c1c00424fd8220e1864afeab3c3d233799fe670e5

coppied from console:

ekholabs-jupyterlab    |         file:///home/jovyan/.local/share/jupyter/runtime/nbserver-7-open.html
ekholabs-jupyterlab    |     Or copy and paste one of these URLs:
ekholabs-jupyterlab    |         http://5a571bebb108:8888/?token=d319142c1c00424fd8220e1864afeab3c3d233799fe670e5
ekholabs-jupyterlab    |      or http://127.0.0.1:8888/ token=d319142c1c00424fd8220e1864afeab3c3d233799fe670e5

**Comment by Mlondo** [comment]
Thanks that work, however when i try to access the following:
http://127.0.0.1:9000/minio/login, it's asking for the access key and secrete key, should I use my generated key under keys?
